#!/bin/sh

##########################################################################
# Name:        stringextract
# Purpose:     Extract strings for translation
# Author:      Dave Page
# Created:     2007-02-13
# RCS-ID:      $Id: stringextract,v 1.1 2008/09/08 13:39:42 dpage Exp $
# Copyright:   (c) EnterpriseDB
# Licence:     BSD Licence
##########################################################################

cp StackBuilder-release.pot StackBuilder.pot

xgettext -k_ -k__ -j -s -o StackBuilder.pot *.cpp
xgettext -k_ -k__ -j -s -o StackBuilder.pot include/*.h

